# Creating Arrays in Python 

In [40]:
import numpy as np
list1=[1,2,3,4]

array1=np.array(list1)

* Converting list to numpy array

In [4]:
array1

array([1, 2, 3, 4])

* Print out array

In [6]:
list2=[11,22,33,44]

In [7]:
mylist=[list1,list2]

* List of two lists 

In [8]:
array=np.array(mylist)

* Array of two lists ( two dimensional array )

In [9]:
array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [25]:
list1

[1, 2, 3, 4]

In [10]:
array.shape

(2, 4)

* Get the size of the array

In [11]:
array.dtype

dtype('int32')

* Find out the data tyoe of the array

In [19]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

* Create array of zeros of size 5

In [20]:
np.zeros((6,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

* Create two dimensional array of zeros of size 6*6

In [41]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

* Create two dimensional array of ones of size 5*5

In [44]:
np.empty((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

* Create empty two dimensional array of size 3*4

In [46]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

* Create two dimensional array of zeros and diameter of ones of size 5*5

In [47]:
np.arange(5)

array([0, 1, 2, 3, 4])

* Using a range